/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import java.util.Date;

/**
 *
 * @author Renniel
 */
public class HeadInventoryDashboard extends javax.swing.JPanel {

    /**
     * Creates new form NewAdminDashboard
     */
    public HeadInventoryDashboard() {
        initComponents();
        setDataToCards();
    }
     public void setDataToCards() {
    long l = System.currentTimeMillis();
    Date todaysDate = new Date();

    try {
         java.sql.Connection con = db.mycon();

        // Get total number of employees
        String employeeQuery = "SELECT COUNT(*) AS total FROM product_package";
        java.sql.PreparedStatement employeeStmt = con.prepareStatement(employeeQuery);
        java.sql.ResultSet employeeRs = employeeStmt.executeQuery();
        if (employeeRs.next()) {
            totalpackage.setText(employeeRs.getString("total"));
        } else {
            totalpackage.setText("0");
        }
        
        
        String categoryQuery = "SELECT COUNT(*) AS total FROM category";
        java.sql.PreparedStatement categoryStmt = con.prepareStatement(categoryQuery);
        java.sql.ResultSet categoryRs = categoryStmt.executeQuery();
        if (categoryRs.next()) {
            category.setText(categoryRs.getString("total"));
        } else {
            category.setText("0");
        }

        
        

        // Get total number of items
        String itemQuery = "SELECT SUM(Current_Stock) AS total_stocks FROM stock_table";
        java.sql.PreparedStatement itemStmt = con.prepareStatement(itemQuery);
        java.sql.ResultSet itemRs = itemStmt.executeQuery();
        if (itemRs.next()) {
            stocks.setText(itemRs.getString("total_stocks"));
        } else {
            stocks.setText("0");
        }
        
        String inventoryQuery = "SELECT COUNT(*) AS total_item FROM product_table";
        java.sql.PreparedStatement inventoryStmt = con.prepareStatement(inventoryQuery);
        java.sql.ResultSet inventoryRs = inventoryStmt.executeQuery();
        if (inventoryRs.next()) {
            item.setText(inventoryRs.getString("total_item"));
        } else {
            item.setText("0");
        }
        

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panelemp7 = new javax.swing.JPanel();
        item = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelemp8 = new javax.swing.JPanel();
        category = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelemp9 = new javax.swing.JPanel();
        stocks = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelemp10 = new javax.swing.JPanel();
        totalpackage = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1290, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(238, 238, 253));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Inventory Head Dashboard");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(916, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        panelemp7.setBackground(new java.awt.Color(239, 239, 255));
        panelemp7.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 0, 102)));

        item.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        item.setForeground(new java.awt.Color(102, 102, 102));
        item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/item.png"))); // NOI18N
        item.setText("0");

        javax.swing.GroupLayout panelemp7Layout = new javax.swing.GroupLayout(panelemp7);
        panelemp7.setLayout(panelemp7Layout);
        panelemp7Layout.setHorizontalGroup(
            panelemp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelemp7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelemp7Layout.setVerticalGroup(
            panelemp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelemp7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Total No. of Items");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Product Category");

        panelemp8.setBackground(new java.awt.Color(239, 239, 255));
        panelemp8.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 0, 102)));

        category.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        category.setForeground(new java.awt.Color(102, 102, 102));
        category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/category.png"))); // NOI18N
        category.setText("0");

        javax.swing.GroupLayout panelemp8Layout = new javax.swing.GroupLayout(panelemp8);
        panelemp8.setLayout(panelemp8Layout);
        panelemp8Layout.setHorizontalGroup(
            panelemp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelemp8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        panelemp8Layout.setVerticalGroup(
            panelemp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelemp8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Total Stocks");

        panelemp9.setBackground(new java.awt.Color(239, 239, 255));
        panelemp9.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 0, 102)));

        stocks.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        stocks.setForeground(new java.awt.Color(102, 102, 102));
        stocks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/item40x40.png"))); // NOI18N
        stocks.setText("0");

        javax.swing.GroupLayout panelemp9Layout = new javax.swing.GroupLayout(panelemp9);
        panelemp9.setLayout(panelemp9Layout);
        panelemp9Layout.setHorizontalGroup(
            panelemp9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelemp9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(stocks, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        panelemp9Layout.setVerticalGroup(
            panelemp9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelemp9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stocks, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 102));
        jLabel9.setText("Total No. of Package");

        panelemp10.setBackground(new java.awt.Color(239, 239, 255));
        panelemp10.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 0, 0, 0, new java.awt.Color(102, 0, 102)));

        totalpackage.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        totalpackage.setForeground(new java.awt.Color(102, 102, 102));
        totalpackage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/item.png"))); // NOI18N
        totalpackage.setText("0");

        javax.swing.GroupLayout panelemp10Layout = new javax.swing.GroupLayout(panelemp10);
        panelemp10.setLayout(panelemp10Layout);
        panelemp10Layout.setHorizontalGroup(
            panelemp10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelemp10Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(totalpackage, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        panelemp10Layout.setVerticalGroup(
            panelemp10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelemp10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalpackage, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelemp10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelemp7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelemp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelemp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelemp7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelemp9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelemp8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(60, 60, 60)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelemp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 81, 1290, 720));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel category;
    private javax.swing.JLabel item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel panelemp10;
    private javax.swing.JPanel panelemp7;
    private javax.swing.JPanel panelemp8;
    private javax.swing.JPanel panelemp9;
    private javax.swing.JLabel stocks;
    private javax.swing.JLabel totalpackage;
    // End of variables declaration//GEN-END:variables
}
